# Generated by Django 5.2.5 on 2025-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='not_completed',
            field=models.BooleanField(default=True),
        ),
    ]
