# Generated by Django 5.2.5 on 2025-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_not_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='not_completed',
            field=models.BooleanField(default=False),
        ),
    ]
