# Generated by Django 5.2.5 on 2025-08-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_not_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='not_completed',
        ),
    ]
